import Head from 'next/head'
import { Header } from 'src/components/Header'
import { MainContainer } from './styles'
import { ServiceCardSection } from 'src/components/CardsGrid'
import { AboutSection } from 'src/components/About'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Na Consulta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <Header />
        <ServiceCardSection />
        <AboutSection />
      </MainContainer>
    </div>
  )
}
