import Head from 'next/head'
import { MainContainer } from './styles'
import { Header } from '@/components/Header'
import { SectionAbout } from '@/components/About'
import { SearchHeader } from 'src/components/SearchHeader'
import { ServiceCardSection } from 'src/components/CardsGrid'
import { DepositionCard } from '@/components/DepositionCard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Na Consulta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <Header />
        <SearchHeader />
        <ServiceCardSection />
        <SectionAbout />
        <DepositionCard />
      </MainContainer>
    </div>
  )
}
